load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_easyhead",
    calculators = ["//mediapipe/graphs/easyhead:easyhead_calculators"],
)
